env:
  contexts:
    - name: "DVWA-Context"
      urls:
        - "http://localhost:4280"
      includePaths:
        - "http://localhost:4280.*"
      authentication:
        method: "browser"
        parameters:
          loginPageUrl: "http://localhost:4280/login.php"
          loginPageWait: 5
        # The standard default credentials for DVWA
        users:
          - name: "admin"
            credentials:
              username: "admin"
              password: "password"
      sessionManagement:
        method: "cookie"
jobs:
  - type: spider
    parameters:
      context: "DVWA-Context"
      user: "admin"
  - type: passiveScan-wait
  - type: activeScan
    parameters:
      context: "DVWA-Context"
      user: "admin"
  - type: report
    parameters:
      template: "modern"
      reportTitle: "DVWA Authenticated Scan Report"
      reportFileName: "zap_report"