on:
  push:
    branches: [ "master" ]


jobs:
  zap-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Check for changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            app_code:
              - 'src/**'      
              - 'Dockerfile'  
              - 'package.json'

      - name: Set up Docker Buildx
        if: steps.filter.outputs.app_code == 'true'
        uses: docker/setup-buildx-action@v3
      - name: Build and Load Image
        if: steps.filter.outputs.app_code == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ghcr.io/digininja/dvwa:latest
          cache-from: type=gha 
          cache-to: type=gha,mode=max

      - name: Start DVWA
        run: docker compose up -d --no-build

      - name: ZAP Authenticated Scan
        uses: zaproxy/action-af@d186d5d9536d0f1380e5eaa58168432fefc8ed6d
        with:
          plan: 'zap-plan.yml'
      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-authenticated-report
          path: zap_report.html

      - name: Install Pandoc
        if: always()
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Process Report Text Safely
        if: always()
        run: |
          if [ -f "zap_report.html" ]
          then
            pandoc zap_report.html -f html -t markdown_strict -o raw_issue.md
            
            head -n 500 raw_issue.md > safe_issue_body.md
            
            echo -e "\n\n...\n**Note:** The vulnerability report was truncated due to length. Please download the full 'zap_report.html' from this workflow's artifacts tab to view all detailed alerts." >> safe_issue_body.md
          else
            echo "Error: zap_report.html not found!"
            exit 1
          fi

      - name: Create GitHub Issue From ZAP Report
        if: always() 
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -f "safe_issue_body.md" ];
          then
            gh label create "security" --color CC0000 --description "Security vulnerabilities" || true
            gh issue create \
              --title "DAST Security Vulnerabilities Found" \
              --body-file safe_issue_body.md \
              --label "security"
              
          else
            echo "No safe_issue_body.md file found. Skipping issue creation."
          fi
          
      - name: Stop App
        if: always()
        run: docker compose down
