on:
  push:
    branches: [ "master" ]


jobs:
  zap-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4

      - name: Check for changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            app_code:
              - 'src/**'       # Adjust these to match your
              - 'Dockerfile'   # app's actual folder structure
              - 'package.json'

      - name: Set up Docker Buildx
        # if: steps.filter.outputs.app_code == 'true'
        uses: docker/setup-buildx-action@v3

      - name: Build and Load Image
        # if: steps.filter.outputs.app_code == 'true'
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true # add to local docker cache
          tags: ghcr.io/digininja/dvwa:latest
          cache-from: type=gha 
          cache-to: type=gha,mode=max

      - name: Start DVWA
        run: docker compose up -d --no-build

      - name: ZAP Authenticated Scan
        uses: zaproxy/action-automation-framework@v0.4.0
        with:
          plan: 'zap-plan.yml'
      - name: Upload ZAP Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-authenticated-report
          path: zap_report.html

      - name: Stop App
        if: always()
        run: docker compose down